name: Telegram-Msg
on:
  workflow_dispatch:

jobs:
  sendMsg:
    name: sendMsg
    runs-on: ubuntu-latest
    steps:
    - uses: colutius/Telegram-Msg@main
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        chatid: ${{ secrets.TELEGRAM_TO }}
